2018-12-16 04:59:48 jdbc[3]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:100)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:138)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:103)
	at org.h2.Driver.connect(Driver.java:69)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:733)
	at org.h2.server.web.WebApp.login(WebApp.java:954)
	at org.h2.server.web.WebApp.process(WebApp.java:211)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:170)
	at org.h2.server.web.WebThread.process(WebThread.java:134)
	at org.h2.server.web.WebThread.run(WebThread.java:90)
	at java.lang.Thread.run(Thread.java:748)

org.h2.message.DbException: アプリケーションにより閉じられていない接続がガベージコレクトされました
The connection was not closed by the application and is garbage collected [90018-197]
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:197)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:137)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:103)
	at org.h2.Driver.connect(Driver.java:69)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:733)
	at org.h2.server.web.WebApp.login(WebApp.java:954)
	at org.h2.server.web.WebApp.process(WebApp.java:211)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:170)
	at org.h2.server.web.WebThread.process(WebThread.java:134)
	at org.h2.server.web.WebThread.run(WebThread.java:90)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.h2.jdbc.JdbcSQLException: アプリケーションにより閉じられていない接続がガベージコレクトされました
The connection was not closed by the application and is garbage collected [90018-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	... 14 more
2018-12-16 05:04:16 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: SQLステートメントに文法エラーがあります "CREATE TABLE ""M_STAFF"" (
  ""STAFF_ID"" VARCHAR(10) PRIMARY KEY COMMENT[*] 'スタッフID'
,  ""STAFF_NAME"" VARCHAR(40) COMMENT 'スタッフ名'
,  ""PASSWORD"" VARCHAR(40) NOT NULL COMMENT 'パスワード'
,  ""CREATED_ID"" VARCHAR(10) COMMENT '作成者ID'
,  ""CREATED_AT"" DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '作成日時'
,  ""UPDATED_ID"" VARCHAR(10) COMMENT '更新者ID'
,  ""UPDATED_AT"" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時'
) "; 期待されるステートメント "HASH, AUTO_INCREMENT, NOT, NULL, CHECK, REFERENCES, ,, )"
Syntax error in SQL statement "CREATE TABLE ""M_STAFF"" (
  ""STAFF_ID"" VARCHAR(10) PRIMARY KEY COMMENT[*] 'スタッフID'
,  ""STAFF_NAME"" VARCHAR(40) COMMENT 'スタッフ名'
,  ""PASSWORD"" VARCHAR(40) NOT NULL COMMENT 'パスワード'
,  ""CREATED_ID"" VARCHAR(10) COMMENT '作成者ID'
,  ""CREATED_AT"" DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '作成日時'
,  ""UPDATED_ID"" VARCHAR(10) COMMENT '更新者ID'
,  ""UPDATED_AT"" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時'
) "; expected "HASH, AUTO_INCREMENT, NOT, NULL, CHECK, REFERENCES, ,, )"; SQL statement:
CREATE TABLE `m_staff` (
  `staff_id` varchar(10) PRIMARY KEY COMMENT 'スタッフID'
,  `staff_name` VARCHAR(40) COMMENT 'スタッフ名'
,  `password` VARCHAR(40) NOT NULL COMMENT 'パスワード'
,  `created_id` VARCHAR(10) COMMENT '作成者ID'
,  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '作成日時'
,  `updated_id` VARCHAR(10) COMMENT '更新者ID'
,  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時'
) [42001-197]
2018-12-16 05:05:57 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: SQLステートメントに文法エラーがあります "CREATE TABLE ""M_STAFF"" (
  ""STAFF_ID"" VARCHAR(10) PRIMARY KEY COMMENT[*] 'スタッフID'
,  ""STAFF_NAME"" VARCHAR(40) COMMENT 'スタッフ名'
,  ""PASSWORD"" VARCHAR(40) NOT NULL COMMENT 'パスワード'
,  ""CREATED_ID"" VARCHAR(10) COMMENT '作成者ID'
,  ""CREATED_AT"" DATETIME DEFAULT CURRENT_TIMESTAMP
,  ""UPDATED_ID"" VARCHAR(10) COMMENT '更新者ID'
,  ""UPDATED_AT"" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) "; 期待されるステートメント "HASH, AUTO_INCREMENT, NOT, NULL, CHECK, REFERENCES, ,, )"
Syntax error in SQL statement "CREATE TABLE ""M_STAFF"" (
  ""STAFF_ID"" VARCHAR(10) PRIMARY KEY COMMENT[*] 'スタッフID'
,  ""STAFF_NAME"" VARCHAR(40) COMMENT 'スタッフ名'
,  ""PASSWORD"" VARCHAR(40) NOT NULL COMMENT 'パスワード'
,  ""CREATED_ID"" VARCHAR(10) COMMENT '作成者ID'
,  ""CREATED_AT"" DATETIME DEFAULT CURRENT_TIMESTAMP
,  ""UPDATED_ID"" VARCHAR(10) COMMENT '更新者ID'
,  ""UPDATED_AT"" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) "; expected "HASH, AUTO_INCREMENT, NOT, NULL, CHECK, REFERENCES, ,, )"; SQL statement:
CREATE TABLE `m_staff` (
  `staff_id` varchar(10) PRIMARY KEY COMMENT 'スタッフID'
,  `staff_name` VARCHAR(40) COMMENT 'スタッフ名'
,  `password` VARCHAR(40) NOT NULL COMMENT 'パスワード'
,  `created_id` VARCHAR(10) COMMENT '作成者ID'
,  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP
,  `updated_id` VARCHAR(10) COMMENT '更新者ID'
,  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) [42001-197]
2018-12-16 05:06:29 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: SQLステートメントに文法エラーがあります "CREATE TABLE ""M_STAFF"" (
  ""STAFF_ID"" VARCHAR(10) PRIMARY KEY COMMENT[*] 'スタッフID'
,  ""STAFF_NAME"" VARCHAR(40) COMMENT 'スタッフ名'
,  ""PASSWORD"" VARCHAR(40) NOT NULL
,  ""CREATED_ID"" VARCHAR(10) COMMENT '作成者ID'
,  ""CREATED_AT"" DATETIME DEFAULT CURRENT_TIMESTAMP
,  ""UPDATED_ID"" VARCHAR(10)
,  ""UPDATED_AT"" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) "; 期待されるステートメント "HASH, AUTO_INCREMENT, NOT, NULL, CHECK, REFERENCES, ,, )"
Syntax error in SQL statement "CREATE TABLE ""M_STAFF"" (
  ""STAFF_ID"" VARCHAR(10) PRIMARY KEY COMMENT[*] 'スタッフID'
,  ""STAFF_NAME"" VARCHAR(40) COMMENT 'スタッフ名'
,  ""PASSWORD"" VARCHAR(40) NOT NULL
,  ""CREATED_ID"" VARCHAR(10) COMMENT '作成者ID'
,  ""CREATED_AT"" DATETIME DEFAULT CURRENT_TIMESTAMP
,  ""UPDATED_ID"" VARCHAR(10)
,  ""UPDATED_AT"" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) "; expected "HASH, AUTO_INCREMENT, NOT, NULL, CHECK, REFERENCES, ,, )"; SQL statement:
CREATE TABLE `m_staff` (
  `staff_id` varchar(10) PRIMARY KEY COMMENT 'スタッフID'
,  `staff_name` VARCHAR(40) COMMENT 'スタッフ名'
,  `password` VARCHAR(40) NOT NULL
,  `created_id` VARCHAR(10) COMMENT '作成者ID'
,  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP
,  `updated_id` VARCHAR(10)
,  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) [42001-197]
2018-12-16 22:26:20 database: flush
org.h2.message.DbException: 一般エラー: "java.lang.IllegalStateException: The file is locked: nio:/Users/kentaro/workspace/ProductMasterMaintenance/db/staff.mv.db [1.4.197/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:/Users/kentaro/workspace/ProductMasterMaintenance/db/staff.mv.db [1.4.197/7]" [50000-197]
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:307)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:95)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:2506)
	at org.h2.mvstore.MVStore.panic(MVStore.java:383)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:364)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2934)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:155)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:100)
	at org.h2.engine.Database.getPageStore(Database.java:2538)
	at org.h2.engine.Database.open(Database.java:709)
	at org.h2.engine.Database.openDatabase(Database.java:286)
	at org.h2.engine.Database.<init>(Database.java:280)
	at org.h2.engine.Engine.openSession(Engine.java:66)
	at org.h2.engine.Engine.openSession(Engine.java:179)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:157)
	at org.h2.engine.Engine.createSession(Engine.java:140)
	at org.h2.engine.Engine.createSession(Engine.java:28)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:351)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:124)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:103)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:571)
	at java.sql.DriverManager.getConnection(DriverManager.java:215)
	at dao.TestStaff.main(TestStaff.java:19)
Caused by: org.h2.jdbc.JdbcSQLException: 一般エラー: "java.lang.IllegalStateException: The file is locked: nio:/Users/kentaro/workspace/ProductMasterMaintenance/db/staff.mv.db [1.4.197/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:/Users/kentaro/workspace/ProductMasterMaintenance/db/staff.mv.db [1.4.197/7]" [50000-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	... 25 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:/Users/kentaro/workspace/ProductMasterMaintenance/db/staff.mv.db [1.4.197/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:870)
	at org.h2.mvstore.FileStore.open(FileStore.java:173)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:350)
	... 19 more
2018-12-17 01:17:47 database: wrong user or password; user: "ROOT"
org.h2.message.DbException: ユーザ名またはパスワードが不正です
Wrong user name or password [28000-197]
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.engine.Engine.openSession(Engine.java:107)
	at org.h2.engine.Engine.openSession(Engine.java:179)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:157)
	at org.h2.engine.Engine.createSession(Engine.java:140)
	at org.h2.engine.Engine.createSession(Engine.java:28)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:351)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:124)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:103)
	at org.h2.Driver.connect(Driver.java:69)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:733)
	at org.h2.server.web.WebApp.test(WebApp.java:892)
	at org.h2.server.web.WebApp.process(WebApp.java:221)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:170)
	at org.h2.server.web.WebThread.process(WebThread.java:134)
	at org.h2.server.web.WebThread.run(WebThread.java:90)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.h2.jdbc.JdbcSQLException: ユーザ名またはパスワードが不正です
Wrong user name or password [28000-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	... 19 more
